### PR TITLE
optimize direct field access

### LINKED ISSUE #42: Field access causes allocations
Accessing fields inside an `@expression` causes allocation, as we end up transforming `x.y` into `getfield(x, :y)`, which can't be inferred (at least in 0.6). For example: 

```julia
frame = CartesianFrame3D()
model = SimpleQP.MockModel()
p = Parameter(model) do
    Point3D(frame, 0., 0., 0.)
end
expr = @expression p.v
SimpleQP.findallocs(expr)
```

gives: 

```
LazyExpression{FunctionWrapper{…}(LazyExpression{Core.#getfield, …}(…))}(…): 112 bytes
  [1]: Parameter{RigidBodyDynamics.Spatial.Point3D{StaticArrays.SArray{Tuple{3},Float64,1,3}}, …}(…): 48 bytes
  [2]: Symbol
```

We probably need to special-case `Core.getfield`.

### PR DESCRIPTION
**Pull request by rdeits**
Fixes #42 

We'll probably need to revisit this in v0.7, since `x.y` gets expanded to the new `getproperty` function.

### CODE REVIEW

**Comment by rdeits** [comment]
By the way, I was worried about this breaking the fully-qualified name fix, but fortunately it all just works. `Base.:+` does get wrapped in a new getfield expression, but then it immediately gets eagerly evaluated and loses its wrapper.

**Comment by tkoolen** [comment]
Hmm, I was expecting just another `optimize` method. Is it really necessary to change the `@expression` macro for this?

**Comment by rdeits** [comment]
I didn't try creating a new optimize method, but I think this is necessary. The problem is that as soon as we treat `Core.getfield(x, :y)` as a regular function call, we lost inferrability because the type of the result depends on the value `:y`.

**Comment by tkoolen** [comment]
I'll give it a shot later today.

**Comment by tkoolen** [comment]
Sorry about the delay, but I think this will work:

```julia
# setup and demonstrate problem
struct Foo
    a::Int
end
using SimpleQP, BenchmarkTools
model = SimpleQP.MockModel()
p = Parameter{Foo}(() -> Foo(3), model)
expr1 = SimpleQP.LazyExpression(Core.getfield, p, :a)
@btime (SimpleQP.setdirty!($p); $expr1()) # allocates

# solve using GetField callable
struct GetField{T} end
(::GetField{T})(arg) where {T} = getfield(arg, T)
expr2 = SimpleQP.LazyExpression(GetField{:a}(), p)
@btime (SimpleQP.setdirty!($p); $expr2()) # doesn't allocate
```

I'll open a PR using this strategy.

**Comment by rdeits** [comment]
Oh yeah, that's good

**Pull request closed without merging**
