### PR TITLE
WIP: Update to MOI 0.5

### PR DESCRIPTION
**Pull request by rdeits**
Supercedes #73 

Requires: 
- [ ] GLPK.jl master
- [ ] https://github.com/JuliaOpt/LinQuadOptInterface.jl/pull/37

@tkoolen I believe I fixed the bug that was present on that LQOI branch (the issue here: https://github.com/JuliaOpt/GLPK.jl/issues/58 is also resolved now). I'm going to see if I can get the LQOI branch merged so we can merge this.

### CODE REVIEW

**Review by tkoolen — APPROVED** [review]
Looks good, thanks. I removed the lower bound on osqp to debug CI builds at some point. Maybe that change should be undone.

**Comment by tkoolen** [comment]
I've triggered a new build since the glpk tag is in.

**Comment by rdeits** [comment]
We'll still need that LQOI branch and maybe also https://github.com/JuliaOpt/GLPK.jl/pull/71

**Comment by tkoolen** [comment]
I want to get a version that supports 1.0 out as soon as possible, so I just disabled the GLPK tests if GLPK doesn't work. I've verified that the tests do pass locally with the LQOI PR branch (+ the `Compat.axes` changes).

**Comment by rdeits** [comment]
I think that's a good decision

**Comment by tkoolen** [comment]
Requires https://github.com/JuliaLang/METADATA.jl/pull/17734.

**Comment by tkoolen** [comment]
Alright, finally.

**Pull request merged**
